name: Run Model 4.0

on:
  workflow_call:
    inputs:
      batch:
        type: string
      datapath:
        type: string
        required: true
      backtest:
        type: string
      task:
        type: string
      seed_set_config:
        type: string
      seeds:
        type: string
      cv_runs:
        type: string
      cross_validation:
        type: string
      config_name:
        type: string
        required: true
      config_override:
        type: string
      region:
        type: string
      gpupool:
        type: string
      gpu_model:
        type: string
      gpu_count:
        type: string
        default: "1"
      procs_per_gpu:
        type: string
      priority:
        type: string
        default: low
    secrets:
      GH_APP_ID:
        required: true
      GH_APP_INSTALLATION_ID:
        required: true
      GH_APP_PRIVATE_KEY:
        required: true
      RUNPOD_API_KEY:
        required: true
      EXPERIMENT_SLACK_WEBHOOK_URL:
        required: true

jobs:
  submit-job:
    runs-on: ${{ inputs.region == 'runpod' && fromJSON('{"group":"ArcCD"}') || fromJSON(format('{{"group":"ArcCD","labels":"{0}"}}', inputs.region)) }}
    steps:
      - name: GitHub login
        id: auth
        uses: TimoWilhelm/action-github-app-auth@v1.0.0
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          installation-id: ${{ secrets.GH_APP_INSTALLATION_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          set-git-credentials: true
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          token: ${{ steps.auth.outputs.access-token }}
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: Submit Job
        env:
          VIRTUAL_ENV: ${{ runner.temp }}/.venv
          INPUT_BATCH: ${{ inputs.batch }}
          INPUT_BACKTEST: ${{ inputs.config_name == 'sanity' && 'sanity' || inputs.backtest }}
          INPUT_TASK: ${{ inputs.config_name == 'sanity' && 'simple_full_short' || inputs.task }}
          INPUT_SEED_SET_CONFIG: ${{ inputs.seed_set_config }}
          INPUT_SEEDS: ${{ inputs.config_name == 'sanity' && 'seed-00' || inputs.seeds }}
          INPUT_CV_RUNS: ${{ inputs.cv_runs }}
          INPUT_CROSS_VALIDATION: ${{ inputs.cross_validation }}
          INPUT_CONFIG_NAME: ${{ inputs.config_name }}
          INPUT_CONFIG_OVERRIDE: ${{ inputs.config_override }}
          INPUT_REGION: ${{ inputs.region }}
          INPUT_GPUPOOL: ${{ inputs.gpupool }}
          INPUT_GPU_MODEL: ${{ inputs.gpu_model }}
          INPUT_GPU_COUNT: ${{ inputs.gpu_count }}
          INPUT_PROCS_PER_GPU: ${{ inputs.procs_per_gpu }}
          INPUT_PRIORITY: ${{ inputs.priority }}
          JOB_MODEL_VERSION: v4
          RUNPOD_API_KEY: ${{ secrets.RUNPOD_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.EXPERIMENT_SLACK_WEBHOOK_URL }}
          AWS_ECR_REGISTRY: 179138733276.dkr.ecr.us-west-2.amazonaws.com
        run: |
          echo "::group::Experiment Parameters"
          echo "batch: ${{ inputs.batch }}"
          echo "datapath: ${{ inputs.datapath }}"
          echo "backtest: $INPUT_BACKTEST"
          echo "task: $INPUT_TASK"
          echo "seed set config: ${{ inputs.seed_set_config }}"
          echo "seeds: $INPUT_SEEDS"
          echo "cv_runs: ${{ inputs.cv_runs }}"
          echo "cross_validation: ${{ inputs.cross_validation }}"
          echo "config name: ${{ inputs.config_name }}"
          echo "config override: ${{ inputs.config_override }}"
          echo "region: ${{ inputs.region }}"
          echo "gpupool: ${{ inputs.gpupool }}"
          echo "gpu_model: ${{ inputs.gpu_model }}"
          echo "gpu_count: ${{ inputs.gpu_count }}"
          echo "procs_per_gpu: ${{ inputs.procs_per_gpu }}"
          echo "priority: ${{ inputs.priority }}"
          echo "::endgroup::"

          python -m venv $VIRTUAL_ENV
          source $VIRTUAL_ENV/bin/activate
          pip install git+https://x-access-token:${{ steps.auth.outputs.access-token }}@github.com/FinAI-Project/compass-mlops.git@main
          python app/single_job.py --data ${{ inputs.datapath }} --job-scheduler kubernetes
